### ISSUE TITLE
net::ER_CONNECTION_REFUSED in the second time i open the app

### ISSUE THREAD

**Issue by MBKayro** [learningequality/kolibri-installer-android#102]
In the first time app install, every thing work fine, then after the second or the 3th times i open the app.

> Webpage not available
> unable to load the web page
> http://127.0.0.1:48955/app/api/initialize/7cb24830408d4 ....
> 
> net::ER_CONNECTION_REFUSED

![Screenshot](https://user-images.githubusercontent.com/328784/161698156-6874e48f-43a9-45fd-b548-b7df61381f18.jpg)

**Comment by rtibbles** [comment]
Interesting - is the foreground service still running when this happens?

**Comment by intelliant01** [comment]
I have experienced this after a few minutes of usage everytime I use the app. I think that it could be the same reason.

Connection to server drops and timer keeps on increasing upon pressing Retry. If a Refresh option shows up, which is not everytime, then it lands up at the below screen -

![IMG_20220412_092733.jpg](https://user-images.githubusercontent.com/2577060/162877643-4e6c42cb-0b5f-4cff-8f45-0f9778ef5ea7.jpg)

Using Kolibri 0.15.1 Android app on

![IMG_20220412_093025__01.jpg](https://user-images.githubusercontent.com/2577060/162877875-69c89e72-d5d2-422d-a47a-fc4de986d103.jpg)

**Comment by rtibbles** [comment]
Is this with a version built from the develop branch, or from the version released on the play store?

If the former, then I think this PR will fix the issue here: https://github.com/learningequality/kolibri/pull/9372

**Comment by MBKayro** [comment]
For me it was 0.15.1, i will test again with the new fix

Le mar. 3 mai 2022 à 00:40, Richard Tibbles ***@***.***> a
écrit :

**Comment by MBKayro** [comment]
tested again, and until now the problem is fixed :)

**Comment by MBKayro** [comment]
Unfortunately, after some days the problems returns :(

**Comment by MBKayro** [comment]
if i delete all user data and cache of the app in phone parameter, the app start the wizard setup normally

**Comment by rtibbles** [comment]
We've been testing the Android app repeatedly and not come across this, so I suspect the updated app architecture is preventing this from happening now. Closing as fixed.

**Comment by rtibbles** [comment]
This should be released in 0.16.0.
