### ISSUE TITLE
SSH using a temp file does not work in Android 10+

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri-installer-android#143]
The reason is the temp pass file has to be inside the `KOLIBRI_DATA` folder, and adb can't write there anymore with the changes in the Android api permissions.

I have checked adb can write in the parent folder, so theoretically it's solvable  adding `..` to https://github.com/learningequality/kolibri-installer-android/blob/develop/src/remoteshell.py#LL70C51-L70C66

This is an important issue when working with provisioning/upgrading scripts on Android devices.

**Comment by jredrejo** [comment]
Changes in 0.16 apk have affected these permissions and now I've been able to confirm we can still write in this directory in Android up to version 13 at least. Honestly, no idea of which of the changes did the trick, but it works with 0.16 apks (not with 0.15.x)

**Comment by rtibbles** [comment]
Excellent news!
