### ISSUE TITLE
Notifications flood

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-installer-android#174]
## Observed behavior
On 3 of my testing devices (Motorola g51 phone with Android 12, Motorola g6 phone with Android 9, and a no-name tablet with Android 11) I'm getting consistent flood of notifications from Kolibri, which pile up and need to be cleared way too often, especially if I leave them idle for hours... If another Android app on my own device were exhibiting this behavior, my first step would be to silence its notifications completely, but then [would it impact syncing](https://github.com/learningequality/kolibri/pull/11525#issuecomment-1816782358)? 

Another thing that I don't recall is when was the last time I saw a modal asking me if I even want to allow notifications from Kolibri? I certainly haven't seen one in several weeks, with numerous APKs I installed, tested, then cleared cache, data, uninstalled , to be able to install again. 

## Errors and logs

Moto g6 | Moto g51
-- | --
https://github.com/learningequality/kolibri-installer-android/assets/1457929/08616be8-9fb5-4261-aea7-779c3b4318ba | https://github.com/learningequality/kolibri-installer-android/assets/1457929/f4bccb6f-192f-48f9-9cf6-6856717f7aa5

## Expected behavior
Not sure if we have discussed and established the appropriate notification frequency, but certainly something less intrusive would offer a better user experience.

## User-facing consequences
The flurry of Kolibris in the upper bar/drawer, and a never-ending list of notifications that need to be cleared. 

## Steps to reproduce
...

## Context
...

cc @rtibbles @bjester

**Comment by rtibbles** [comment]
> Another thing that I don't recall is when was the last time I saw a modal asking me if I even want to allow notifications from Kolibri? I certainly haven't seen one in several weeks, with numerous APKs I installed, tested, then cleared cache, data, uninstalled , to be able to install again.

Android has centralized the management of notifications into the OS itself - so this is down to the Android user making these selections in the notifications settings.

I had suspected that silencing notifications might have a negative impact on syncing: https://github.com/learningequality/kolibri/pull/11525#issuecomment-1816782358 - but looking through the logs in more detail, it didn't seem to be a contributing factor.

**Comment by radinamatic** [comment]
Ok, I'll silence these notifications and see if it makes any difference...
(edited) Apologies, I'm not reading well today... 🤦🏽‍♀️

**Comment by pcenov** [comment]
@rtibbles a note here, that I am not seeing any notifications on my Samsung phone running on Android 13. Apparently they've made changes to that version of Android so that all notifications are off by default. Since Kolibri is not showing a permissions dialogue in which one can opt to see the notifications they are not being displayed at all.

**Comment by rtibbles** [comment]
@pcenov thanks - I had noticed similar when testing on an emulator. Given that our current main reason for displaying notifications is Android needing us to for some background processing tasks, I am ok with this, as their being silenced doesn't seem to affect the task processing.

Some of the notifications are a little more informative, but we can work to surface those to the user in the future!
