### ISSUE TITLE
Some ui-icons do not render

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri-installer-android#18]
Some `ui-icons` do not render, or incorrectly render in some webviews. This issue was noted on the $10 phone.
```html
<!--DOES NOT RENDER-->
<i class="material-icons">view_module</i>
<ui-icon icon="view_module"/>    

<!--DOES RENDER-->
<i class="material-icons">&#xE8F0;</i>  
<mat-svg category="action" name="view_module"/>
<ui-icon><mat-svg category="action" name="view_module"/></ui-icon>
```

Seems like this is due to the webview not supporting ligatures.

A solution would be to use the following markup
```html
<ui-icon ariaLabel="Label">
  <mat-svg category="action" name="view_module"/>
</ui-icon>
```

This would allow us to benefit from the styling and accessibility of the `ui-icon`. We could also simplify this, by creating a `k-icon` component.

```html
<k-icon ariaLabel="lit">
  <mat-svg name="lit" category="life">
</k-icon>
<k-icon ariaLabel="label">
  <file-svg src="./customicon.svg"/>
</k-icon>
```

**Comment by indirectlylit** [comment]
I like the idea of adding a core k-icon component. However I don't think we should be creating a styleguide page for it

**Comment by christianmemije** [comment]
This was fixed in https://github.com/learningequality/kolibri/pull/3708

**Comment by indirectlylit** [comment]
great!
