### ISSUE TITLE
Investigate changing p4a to store and load python in apk

### ISSUE THREAD

**Issue by kollivier** [learningequality/kolibri-installer-android#25]
Initially, p4a was going to simply copy the entire Python distro into the apk, and run it from there. However, this failed due to the Android toolchain deleting some files during build. The only details I could find on this issue were in a comment here:

https://github.com/kivy/python-for-android/issues/202#issuecomment-53153860

Given how long ago the comment was, and how little is known about the severity of the problem, it may be worth investigating whether or not we can make this process work now. This should probably be after the current milestone, but this would massively speed up initial load on old devices, and even newer ones, so I think it's worth at least a little time to investigate.

**Comment by david672orford** [comment]
I have been looking into this. There is a bug report about the Android toolchain failing to pack asset files with names beginning with an underscore:

  https://issuetracker.google.com/issues/36911326

The message describing the fix says in part:

> In tools r20 with platform-tools r12, this will be fixed by setting a property named "aapt.ignore.assets" in project.properties using the format explained in https://android-review.googlesource.com/#/c/36532/4/files/ant/build.xml

I have tried the fix and it does work.

Python is happy to load its libraries directly out of the apk using zipimport. However, it will not load them if they are double zipped, you have to unpack python27.zip. Also, it will not load .so files directly out of a zip file. The solution is to add stub .py versions which unpack them to the application's cache directory and then load them. (This solution is using in .egg files.)

I have more information and sample code which I can share if anyone is interested.

**Comment by kollivier** [comment]
Awesome, thanks for working on this! Yes, I'd love to see any information and particularly any sample code you have on this!

**Comment by kollivier** [comment]
Would love to see any

**Comment by kollivier** [comment]
Would love to see any

**Comment by david672orford** [comment]
I have it to the point of running hello-world apps. Here it is:
https://github.com/david672orford/android-webview-wsgi

**Comment by david672orford** [comment]
This series of articles may provide some insights into how the present design was arrived at:
http://joaoventura.net/blog/2014/python-android/
I don't know if the present Python for Android bootstraps are based on these articles or the articles are based on the bootstraps. Either way, the code is almost identical and the discussion is interesting. The idea of putting the standard library into a ZIP file inside the Tar file inside the Apk is even suggested by a reader in the comments.

**Comment by david672orford** [comment]
Yes, you can do that. Just remove the code to start the web server from bootstrap.py and use this instead:

    import runpy
    runpy.run_module("main", run_name="__main__")

This is definitely what you should do if you are incorporating these changes into the sdl2 or pygame backend. But for a webview bootstrap you aren't really doing the user any favors since now he has to put the code you removed into main.py. Without it automatic port assignment will not work and the application will likely have security vulnerabilites since any app on the device can send requests to the web server. In contrast my solution only requires him to make sure his code will not execute app.run() when imported.

**Comment by kollivier** [comment]
I will have to take a closer look at the code to understand the security concerns, but Kolibri has it's own code for starting the server and this process takes time so we must show a loading screen regardless. Note that what we did in our case was to write some custom Python code that gives us access to the PythonActivity and the Android WebView in Python (using pyjnius), so that we can control the start up experience and tailor it to our app's needs. In our custom webview bootstrap, we removed the loading page logic and just created our own loading process instead. We're hoping to upstream the changes that are generalizable, and then possibly create a custom bootstrap for the parts that are specific to Kolibri's needs. (There is some work being done in p4a for bootstraps to share code so that custom bootstraps will be smaller and easier to create when needed.)

**Comment by david672orford** [comment]
That sounds almost exactly like what I did, though I didn't use Pyjnius. Instead I added a function in C called android.load_url(). It is called at the end of bootstrap.py.
I am glad to hear there is an effort to reduce the code duplication in the bootstraps. Once that is done incorporating my changes would be much easier.
