### ISSUE TITLE
Learner cannot see class video or topic - just a blank page with title on top.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri-installer-android#60]
### Observed behavior
Learner cannot see the class topic or video - just sees a blank page with the topic title on top.  The quiz section worked though.

![2020-05-07-thu--android testing - add by 10 issue](https://user-images.githubusercontent.com/175580/81286521-c355e500-9093-11ea-8afd-19e0dca9b5d4.gif)

The coach and admin however can see the class topic or video.
![2020-05-07-thu--android testing - add by 10 issue 2](https://user-images.githubusercontent.com/175580/81286560-d4065b00-9093-11ea-9ac0-1b1c2d10d6e5.gif)

### Expected behavior
Learner should see the class topic.

### User-facing consequences
Learner is confused whether to wait for the page 

### Errors and logs
Took this from the Android VM at `sdcard/Android/data/org.learningequality.Kolibri/files/KOLIBRI_DATA/logs/` folder.  The `debug.txt` file has no content.

[kolibri.txt](https://github.com/learningequality/kolibri-installer-android/files/4592513/kolibri.txt)

### Steps to reproduce
1. Use the "Radina test channel" and TESSA for sample channels.
1. Create a coach, plan a class, then assign contents.
1. Create a learner, assign to a class, then access the class content.

### Context
Tell us about your environment, including:
* Kolibri version: 0.13.3a0.dev0+git.18....205f downloaded the [build 144 of Android .apk from BuildKite](https://buildkite.com/learningequality/kolibri-android-installer/builds/144#36249ca3-3fd8-450c-bd20-dc3efc373435)
* Operating system: Android 7.1.2 on BlueStacks emulator
* Browser: n/a

**Comment by mrpau-julius** [comment]
Confirm, that this issue is also exist in Android devices OS version 7 and 9.
![Screenshot_20200511_063617_org learningequality Kolibri](https://user-images.githubusercontent.com/38421180/81512476-596b6300-9353-11ea-8bb4-e4e1d472c2d7.jpg)

**Comment by mrpau-julius** [comment]
This issue is on the Kolibri apps itself because I try it to use to my android device to serve as a server. I used a laptop to check if this bug exists and followed the step to reproduce. It seems it's working on my laptop. All the content is well displayed.
![Screen Shot 2020-05-11 at 5 52 44 PM](https://user-images.githubusercontent.com/38421180/81548848-7d10c680-93b0-11ea-9a78-406275db923a.png)
