### ISSUE TITLE
Login textbox is very laggy and misses keys pressed.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri-installer-android#61]
### Observed behavior
Login textbox is very laggy and misses keys pressed.

Solution was to click outside the textbox then click on the textbox again.  Notice on the .gif below that the "virtual keyboard" icon appeared at the upper left portion of the screen as I did this.  The textbox worked after this.

I'm not sure if this is because I'm using BlueStacks emulator or not.  I will try this on Android Studio emulator (still downloading) or another emulator.

![2020-05-07-thu--android testing - login typing issue](https://user-images.githubusercontent.com/175580/81288847-f8fccd00-9097-11ea-877f-de9244319b2f.gif)

### Expected behavior
Login textbox should work properly.

### User-facing consequences
User gets frustrated by the laggy and missing keys pressed behavior.

### Errors and logs
Took this from the Android VM at `sdcard/Android/data/org.learningequality.Kolibri/files/KOLIBRI_DATA/logs/` folder.  The `debug.txt` file has no content.

[kolibri.txt](https://github.com/learningequality/kolibri-installer-android/files/4592611/kolibri.txt)

### Steps to reproduce
1. Install and setup Kolibri Android .apk build 144 linked below.
1. Create users and attempt to login them.

### Context
Tell us about your environment, including:
* Kolibri version: 0.13.3a0.dev0+git.18....205f downloaded the [build 144 of Android .apk from BuildKite](https://buildkite.com/learningequality/kolibri-android-installer/builds/144#36249ca3-3fd8-450c-bd20-dc3efc373435)
* Operating system: Android 7.1.2 on BlueStacks emulator
* Browser: n/a

**Comment by jamalex** [comment]
We should confirm that this is no longer happening.

**Comment by radinamatic** [comment]
Thnak you @pcenov, I had a feeling this was due to the Bluestacks emulator (it was always laggy as heck for me 😒). Closing!
