### ISSUE TITLE
P2P Import has an empty channels and resources

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri-installer-android#62]
### Observed behavior

Using local networks or Peer to Peer (P2P), Super admin cannot see the channels and resources to import even if the other devices have the channels available.  

![SVID_20200519_113003_1](https://user-images.githubusercontent.com/38421180/82283821-0ab06f80-99ca-11ea-82a1-39c6e8cbdddf.gif)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

* Kolibri version : 0.13.3a0.dev0+git.18.g5c58205f download in google play store
 * Operating system: Android 9.0 (Pie) Huawei Y6s
 * Browser n/a

**Comment by jamalex** [comment]
Working now!
