### ISSUE TITLE
app has incorrect icon

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-installer-android#63]
We currently use this icon:

https://github.com/learningequality/kolibri-installer-android/blob/develop/icon.png

We should be using this icon:

![kolibri](https://user-images.githubusercontent.com/2367265/82719142-ec15d700-9c5c-11ea-839e-c75a3cb0a793.png)

**Comment by indirectlylit** [comment]
@kollivier @jonboiser flagging that this is still the case

Noticed in this work: https://learningequality.slack.com/archives/C5XMC1EAV/p1604555990025800

![image](https://user-images.githubusercontent.com/2367265/98594454-88727b00-2289-11eb-85d6-1d5aebc53e5b.png)

![image](https://user-images.githubusercontent.com/2367265/98594468-8d372f00-2289-11eb-8808-93d49cbbd749.png)

**Comment by indirectlylit** [comment]
hooray!

**Comment by rtibbles** [comment]
This is slightly presumed - as I have followed the Play Store guidelines, which actually requires an un-bordered icon image, when you publish to the play store, they mask it for you.
