### ISSUE TITLE
Loading image (instead of black screen)

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri-installer-android#7]
Happens on first time opening, while things are unpacking.

**Comment by christianmemije** [comment]
The issue was that the default loading screen was only being removed in the dockerfile, not in the local build. Should be fixed in https://github.com/learningequality/kolibri-kivy/pull/14/. Can you confirm @DXCanas ?

**Comment by christianmemije** [comment]
I was looking at the `presplash_image` or `presplash_color` config parameters, but it looks like they are not implemented in the webview bootstrap, only in the sdl2 bootstrap 

https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java#L404

https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/webview/build/src/org/kivy/android/PythonActivity.java

**Comment by jamalex** [comment]
I believe this has been improved, but we should confirm.

**Comment by rtibbles** [comment]
This has indeed been updated.
