### ISSUE TITLE
Service to Keep App Alive in Background

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri-installer-android#8]
Currently, low end devices kill the service the moment you leave the app.

**Comment by DXCanas** [comment]
Discussions with @kollivier, @indirectlylit, and @jamalex led to decision that, for now, best approach would be to store URL state and persist when the app is awoken. Removing from this milestone for now.

**Comment by jamalex** [comment]
Now exists, with a persistent notification to avoid accidental closure (plus we also have URL-state-resumption).
