### ISSUE TITLE
Launch Kolibri with the appropriate installer type env var set

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-installer-android#84]
In line with learningequality/kolibri#7957 the batch file for launching Kolibri should properly set KOLIBRI_INSTALLATION_TYPE to:

`apk - {KOLIBRI_APK_VERSION_NAME}`

**Comment by jamalex** [comment]
Wooooo! Fixed by spec -- it already does the right thing!
https://github.com/learningequality/kolibri/issues/7960
