### ISSUE TITLE
Fullscreen not working for videos on Android

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri-installer-android#86]
Note: this is different from https://github.com/learningequality/kolibri-app/issues/5 (which was macOS-specific)

While full-screen seems to work for documents, HTML5, etc, the button is disabled on videos. This can impair the ability to watch the full video frame on some screen sizes, and not fully leverage the screen when on smaller screens.

**Comment by intelliant01** [comment]
Seems similar to https://github.com/learningequality/kolibri/issues/7537

**Comment by rtibbles** [comment]
I think this StackOverflow answer might give us some guidance to making updates to the WebView to allow this: https://stackoverflow.com/a/56186877
