### ISSUE TITLE
Older <4.4 Android Compatibility

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri-installer-android#9]
Notes:
- https://github.com/kivy/python-for-android/pull/903

**Comment by christianmemije** [comment]
The issue appears to be with loading sqlite3 https://github.com/kivy/python-for-android/issues/925

**Comment by jamalex** [comment]
Based on barriers around target API versions and Play Store requirements, I don't think we're pushing for versions older than this now.
