### ISSUE TITLE
Kolibri Android App - 'Webpage not available' message is displayed after launching the app

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri-installer-android#92]
## Observed behavior
I'm seeing a 'Webpage not available' message after launching the Android app which disappears after 15-20 seconds and then I can interact normally with the app.

## Steps to reproduce the issue
1. Install the following Android build: https://buildkite.com/learningequality/kolibri-android-installer/builds/3613
2. Launch the app
3. Observe that an error screen is displayed and only after waiting about 15-20 seconds I can actually see the app fully loaded

## Additional information
![Screenshot_20211214-165753_Kolibri](https://user-images.githubusercontent.com/79847249/146022948-46acc406-35c7-4fa8-b27e-b24bc8095b99.jpg)

## Logs and DB files: 
[AndroidLogsAndDB.zip](https://github.com/learningequality/kolibri/files/7712473/AndroidLogsAndDB.zip)

## Usage Details
 - OS: Android 7, Samsung S7

**Comment by radinamatic** [comment]
This has been fixed last week when we released the new 0.16 alpha, is it alive and working for 0.15 too? @rtibbles
