### ISSUE TITLE
make run_docker fails while trying to download pip

### ISSUE THREAD

**Issue by samwagg** [learningequality/kolibri-installer-android#98]
```
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.

The command '/bin/sh -c curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py' returned a non-zero code: 1
```

I noticed you have a ticket for upgrading python. As a short time fix, changing the URL as suggested by the error message works, but I'm not sure if hardcoding 3.6 is desirable.

**Comment by MBKayro** [comment]
i think it was moved to https://bootstrap.pypa.io/pip/3.6/get-pip.py

**Comment by rtibbles** [comment]
This was fixed in https://github.com/learningequality/kolibri-installer-android/commit/53fd490ad1c35fce3a59c2e436ebad74a4fa5bc7
